import ContextProvider from "@/context/ContextProvider";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Task App Prisma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <ToastContainer />
          <main className="md:flex h-screen">
            <div className="w-1/3 md:h-auto bg-cover bg-center bg-barber"></div>

            <div className="md:w-2/3 py-20 px-8 overflow-y-scroll">{children}</div>
          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
